# -*- coding: utf-8 -*-
"""Cleaning_Stephanie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N50RrnqjOY7sVeMAo0SKq2jIo2MiIKD5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error

from sklearn.linear_model import Lasso

from sklearn.linear_model import LassoCV

from keras import Sequential
from keras.layers import Dense, Embedding, LSTM, GRU
from keras.layers import Dropout, LeakyReLU
from keras.callbacks import EarlyStopping
from keras.layers import BatchNormalization, LayerNormalization
from tensorflow.keras.optimizers import Adam

from sklearn.model_selection import TimeSeriesSplit

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV

from sklearn.model_selection import TimeSeriesSplit
from sklearn.base import clone
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

#Temp Cleaning

def Air_Temp_Cleaning(df):

  #time as index
  df["time"] = pd.to_datetime(df["time"])
  df = df.set_index("time")

  #-----------------
  features = ["AT", "ATA", "TX", "TN"]

  df_clean=df.copy()  #Copy of df
  df_No_NaN = df.dropna(subset=features + ["PR"]) #Df without NaN

   #-----------------

  # PR Model

  features = ["AT", "ATA", "TX", "TN"]

  df_No_NaN = df.dropna(subset=features + ["PR"])

  X = df_No_NaN[features]
  y = df_No_NaN["PR"]

  #-----------------

  X_train, X_test, y_train, y_test = train_test_split(
      X, y,
      test_size=0.2,
      shuffle=False
  )

  model_PR_Complete = RandomForestRegressor(
      n_estimators=10,
      random_state=996, #Seed
      verbose=2
  )

  model_PR_Complete.fit(X_train, y_train)

  y_pred = model_PR_Complete.predict(X_test)

  mae = mean_absolute_error(y_test, y_pred)
  rmse = np.sqrt(mean_squared_error(y_test, y_pred))

  #Model PR Testing

  print("MAE PR Model:", mae)
  print("RMSE PR Model:", rmse)

  #Fullfile PR after initial gap

  Indicator_PR_Complete = df_clean["PR"].isna() & df_clean[features].notna().all(axis=1)

  X_missing = df_clean.loc[Indicator_PR_Complete, features]

  print("PR fitted:", Indicator_PR_Complete.sum())

  df_clean.loc[Indicator_PR_Complete, "PR"] = model_PR_Complete.predict(X_missing)

  #Interpolate AT, ATA, TX and TN because they are easy variables

  df_clean[["AT","ATA","TX","TN"]] = df_clean[["AT","ATA","TX","TN"]].interpolate(method="time")

  #Initial ATA Gap Model

  features = ["AT", "TX", "TN"]

  df_ata_NaN = df.dropna(subset=["ATA"] + features)

  X = df_ata_NaN[features]
  y = df_ata_NaN["ATA"]

  X_train, X_test, y_train, y_test = train_test_split(
      X, y,
      test_size=0.2,
      shuffle=False
  )

  model_ata = RandomForestRegressor(
      n_estimators=10,
      random_state=996, #Seed
      verbose=2
  )

  model_ata.fit(X_train, y_train)

  #ATA Model Testing

  y_pred = model_ata.predict(X_test)

  mae = mean_absolute_error(y_test, y_pred)
  rmse = np.sqrt(mean_squared_error(y_test, y_pred))

  print("MAE ATA:", mae)
  print("RMSE ATA:", rmse)

  #ATA fullfilment

  df_ata_NaN_idx = df_clean["ATA"].isna() & df_clean[features].notna().all(axis=1)

  X_missing = df_clean.loc[df_ata_NaN_idx, features]

  print("ATA fitted:", df_ata_NaN_idx.sum())

  df_clean.loc[df_ata_NaN_idx, "ATA"] = model_ata.predict(X_missing)

  #PR fullfilment in initial GAP

  features = ["AT", "ATA", "TX", "TN"]

  Indicator_PR_Complete = df_clean["PR"].isna() & df_clean[features].notna().all(axis=1)

  X_missing = df_clean.loc[Indicator_PR_Complete, features]

  df_clean.loc[Indicator_PR_Complete, "PR"] = model_PR_Complete.predict(X_missing)

  #New Data Document
  df_clean.to_csv("df_Air_Temp_clean.csv", index=True)


# Rad Cleaning
def Air_Rad_Cleaning(df):

    # Set up

    df["time"] = pd.to_datetime(df["time"])
    df = df.set_index("time")

    # REAL copy
    df_clean = df.copy()

    # Interpolate easy variables FIRST

    df_clean[["HU", "WS"]] = (
        df_clean[["HU", "WS"]]
        .interpolate(method="time")
    )

    # IR Model

    features = ["HU", "WS"]

    df_IR = df_clean.dropna(subset=features + ["IR"])

    print("IR training samples:", len(df_IR))

    if len(df_IR) > 0:

        X = df_IR[features]
        y = df_IR["IR"]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=0.2,
            shuffle=False
        )

        model_IR = RandomForestRegressor(
            n_estimators=200,
            random_state=996,
            n_jobs=-1
        )

        model_IR.fit(X_train, y_train)

        # Testing
        y_pred = model_IR.predict(X_test)

        mae = mean_absolute_error(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))

        print("MAE IR:", mae)
        print("RMSE IR:", rmse)

        # Fill IR
        df_IR_NaN_idx = (
            df_clean["IR"].isna()
            & df_clean[features].notna().all(axis=1)
        )

        X_missing = df_clean.loc[df_IR_NaN_idx, features]

        print("IR fitted:", df_IR_NaN_idx.sum())

        df_clean.loc[df_IR_NaN_idx, "IR"] = (
            model_IR.predict(X_missing)
        )

    else:
        print("No valid samples for IR model")

    # HUA Model

    features = ["HU", "WS", "IR"]

    df_HUA = df_clean.dropna(subset=features + ["HUA"])

    print("HUA training samples:", len(df_HUA))

    if len(df_HUA) > 0:

        X = df_HUA[features]
        y = df_HUA["HUA"]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=0.2,
            shuffle=False
        )

        model_HUA = Pipeline([
            ("scaler", StandardScaler()),
            ("lasso", LassoCV(
                cv=5,
                random_state=996,
                max_iter=10000
            ))
        ])

        model_HUA.fit(X_train, y_train)

        # Testing
        y_pred = model_HUA.predict(X_test)

        mae = mean_absolute_error(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))

        print("MAE HUA:", mae)
        print("RMSE HUA:", rmse)

        # Fill HUA
        df_HUA_NaN_idx = (
            df_clean["HUA"].isna()
            & df_clean[features].notna().all(axis=1)
        )

        X_missing = df_clean.loc[df_HUA_NaN_idx, features]

        print("HUA fitted:", df_HUA_NaN_idx.sum())

        df_clean.loc[df_HUA_NaN_idx, "HUA"] = (
            model_HUA.predict(X_missing)
        )

    else:
        print("No valid samples for HUA model")

    # WSA Model

    features = ["HU", "WS", "IR"]

    df_WSA = df_clean.dropna(subset=features + ["WSA"])

    print("WSA training samples:", len(df_WSA))

    if len(df_WSA) > 0:

        X = df_WSA[features]
        y = df_WSA["WSA"]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=0.2,
            shuffle=False
        )

        model_WSA = Pipeline([
            ("scaler", StandardScaler()),
            ("lasso", LassoCV(
                cv=5,
                random_state=996,
                max_iter=10000
            ))
        ])

        model_WSA.fit(X_train, y_train)

        # Testing
        y_pred = model_WSA.predict(X_test)

        mae = mean_absolute_error(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))

        print("MAE WSA:", mae)
        print("RMSE WSA:", rmse)

        # Fill WSA
        df_WSA_NaN_idx = (
            df_clean["WSA"].isna()
            & df_clean[features].notna().all(axis=1)
        )

        X_missing = df_clean.loc[df_WSA_NaN_idx, features]

        print("WSA fitted:", df_WSA_NaN_idx.sum())

        df_clean.loc[df_WSA_NaN_idx, "WSA"] = (
            model_WSA.predict(X_missing)
        )

    else:
        print("No valid samples for WSA model")

    # Save csv

    df_clean.to_csv("df_Air_Rad_clean.csv", index=True)

    return df_clean

#Repeated Values Using Percentil

def repeated_values(df,eps=1e-4,percentil=.99):

    df_clean_stuck = df.copy()
    for col in df_clean_stuck.columns:

      s = df_clean_stuck[col]

      change = s.diff().abs() > eps
      groups = change.cumsum()

      run_length = s.groupby(groups).transform("size")

      # distribución propia
      lengths = run_length.dropna()

      th = lengths.quantile(percentil)

      mask = run_length > th

      df_clean_stuck.loc[mask, col] = np.nan

    return df_clean_stuck

#Returns

def conditional_returns(df, th=3,low=0.001,up=0.999):
    result = pd.DataFrame(index=df.index)

    for col in df.columns:

        s = df[col]

        # Consecutuve gaps size
        gap_sizes = s.isna().groupby((~s.isna()).cumsum()).transform("sum")

        returns = pd.Series(np.nan, index=s.index)

        last_valid_value = None
        gap_count = 0

        for i in range(len(s)):

            val = s.iloc[i]

            if pd.isna(val):
                gap_count += 1
                continue

            # Firs value not NaN
            if last_valid_value is None:
                last_valid_value = val
                gap_count = 0
                continue

            # If gap <= th
            if gap_count <= th:
                # Net return
                returns.iloc[i] = val - last_valid_value
                #Proportion return
                #returns.iloc[i] = (val / last_valid_value) - 1

            # If gap >= th
            else:
                returns.iloc[i] = np.nan

            last_valid_value = val
            gap_count = 0

        result[col] = returns

    # percentile by columns
    lower = result.quantile(low)   # 0.1%
    upper = result.quantile(up)   # 99.9%
    returns_per_clean = result.mask((result < lower) | (result > upper))

    return result, returns_per_clean


#Percentil Outliers

def soil_temp_percentil_outliers(df,low=0.001,up=0.999,th_returns=3):

    variables = df.columns.values

    returns,returns_per_clean=conditional_returns(df,th_returns)
    df_Clean_per = df.copy()

    # percentile by columns
    lower = returns.quantile(low)   # 0.1%
    upper = returns.quantile(up)   # 99.9%

    # outliers
    outlier_mask = (returns < lower) | (returns > upper)

    #Final Mask
    final_mask = outlier_mask

    # Apply mask to temperature dataset instead returns
    df_Clean_per[variables] = df_Clean_per[variables].mask(final_mask)

    return df_Clean_per, returns_per_clean


#Percentil Outliers neighborhood Usnig Fixed Jump Lenght

def soil_temp_percentil_neighborhood_outliers_fix_jump(df,low=0.001,up=0.999,th_returns=3,sens_stuck=20,segment_th = 20):

    variables = df.columns.values

    returns,returns_per_clean=conditional_returns(df,th_returns)
    df_Clean_per = df.copy()

    # percentile by columns
    lower = returns.quantile(low)   # 0.1%
    upper = returns.quantile(up)   # 99.9%

    # outliers
    outlier_mask = (returns < lower) | (returns > upper)

    # STUCK SENSOR

    mask_stuck = pd.DataFrame(
        False,
        index=returns.index,
        columns=returns.columns
    )

    for col in returns.columns:

        diff = returns[col].diff().abs()

        stuck = diff < 1e-6

        groups = (stuck != stuck.shift()).cumsum()

        run_length = stuck.groupby(groups).transform("sum")

        mask_stuck[col] = run_length >= sens_stuck

    # Neighborhood

    mask_transient = pd.DataFrame(
        False,
        index=df.index,
        columns=df.columns
    )

    for col in df.columns:

        s = df[col]

        # diferencias
        diff = s.diff()

        # jumps positivos y negativos
        pos_jump = diff > upper[col]
        neg_jump = diff < lower[col]

        pos_idx = np.where(pos_jump)[0]
        neg_idx = np.where(neg_jump)[0]

        # revisar pares
        for p in pos_idx:

            # negativos posteriores cercanos
            nearby_neg = neg_idx[
                (neg_idx > p) &
                (neg_idx - p <= segment_th)
            ]

            if len(nearby_neg) > 0:

                n = nearby_neg[0]

                # eliminar segmento completo
                mask_transient.iloc[p:n+1,
                                    mask_transient.columns.get_loc(col)] = True

        # también al revés
        for n in neg_idx:

            nearby_pos = pos_idx[
                (pos_idx > n) &
                (pos_idx - n <= segment_th)
            ]

            if len(nearby_pos) > 0:

                p = nearby_pos[0]

                mask_transient.iloc[n:p+1,
                                    mask_transient.columns.get_loc(col)] = True

    # FINAL MASK

    final_mask = (
        mask_stuck |
        outlier_mask |
        mask_transient
    )

    # apply mask to temperatures
    df_Clean_per[variables] = (
        df_Clean_per[variables]
        .mask(final_mask)
    )

    return df_Clean_per, returns_per_clean

#Percentil Outliers neighborhood Usnig Dynimic Jump Lenght

# Percentile Outliers Neighborhood Using Dynimic Jump Lenght

def soil_temp_percentil_neighborhood_outliers(
    df,
    low=0.001,
    up=0.999,
    th_returns=3,
    sens_stuck=20,
    segment_th=20
):

    variables = df.columns.values

    returns, returns_per_clean = conditional_returns(df, th_returns)

    df_clean_per = df.copy()

    # Percentile Outliers

    lower = returns.quantile(low)
    upper = returns.quantile(up)

    outlier_mask = (
        (returns < lower) |
        (returns > upper)
    )

    # STUCK SENSOR

    mask_stuck = pd.DataFrame(
        False,
        index=returns.index,
        columns=returns.columns
    )

    for col in returns.columns:

        diff = returns[col].diff().abs()

        stuck = diff < 1e-6

        groups = (stuck != stuck.shift()).cumsum()

        run_length = stuck.groupby(groups).transform("sum")

        mask_stuck[col] = run_length >= sens_stuck

    # CHANGE-POINT NEIGHBORHOODS

    mask_transient = pd.DataFrame(
        False,
        index=returns.index,
        columns=returns.columns
    )

    for col in returns.columns:

        r = returns[col]

        # diferencias absolutas
        diff = r.diff().abs()

        # threshold robusto usando percentil
        jump_threshold = np.nanpercentile(
            diff.dropna(),
            99
        )

        # jumps grandes
        jump = diff > jump_threshold

        # expandir alrededor del jump
        expanded = jump.copy()

        for i in range(1, segment_th + 1):

            expanded |= jump.shift(i, fill_value=False)

            expanded |= jump.shift(-i, fill_value=False)

        # incluir NaNs dentro del segmento
        nan_regions = (
            r.isna()
            .rolling(segment_th, min_periods=1)
            .max()
            .astype(bool)
        )

        expanded |= nan_regions

        mask_transient[col] = expanded.fillna(False)

    # FINAL MASK

    final_mask = (
        outlier_mask |
        mask_stuck |
        mask_transient
    )

    # apply mask
    df_clean_per[variables] = (
        df_clean_per[variables]
        .mask(final_mask)
    )

    return df_clean_per, returns_per_clean


#Zscores Outliers neighborhood Using Fixed Jump Lenght

def soil_temp_zscores_neighborhood_outliers_fix_jump(df,zscr_sd=3,th_returns=3,sens_stuck=20,segment_th = 20):

    variables = df.columns.values

    returns,returns_per_clean=conditional_returns(df,th_returns)
    df_Clean_per = df.copy()

    # TEMPERATURE returns Z-SCORE

    mean_ret = returns.mean()

    std_ret = returns.std()

    z_temp = (
        (returns - mean_ret)
        / std_ret
    )

    # only upper outliers > 2 SD
    zscore_mask = abs(z_temp) > zscr_sd*std_ret

    # STUCK SENSOR

    mask_stuck = pd.DataFrame(
        False,
        index=returns.index,
        columns=returns.columns
    )

    for col in returns.columns:

        diff = returns[col].diff().abs()

        stuck = diff < 1e-6

        groups = (stuck != stuck.shift()).cumsum()

        run_length = stuck.groupby(groups).transform("sum")

        mask_stuck[col] = run_length >= sens_stuck

    # Vecindades

    mask_transient = pd.DataFrame(
        False,
        index=df.index,
        columns=df.columns
    )

    for col in returns.columns:

        z = z_temp[col]

        # jumps positivos y negativos
        pos_jump = z > zscr_sd
        neg_jump = z < -zscr_sd

        pos_idx = np.where(pos_jump)[0]
        neg_idx = np.where(neg_jump)[0]

        # revisar pares
        for p in pos_idx:

            # negativos posteriores cercanos
            nearby_neg = neg_idx[
                (neg_idx > p) &
                (neg_idx - p <= segment_th)
            ]

            if len(nearby_neg) > 0:

                n = nearby_neg[0]

                # eliminar segmento completo
                mask_transient.iloc[p:n+1,
                                    mask_transient.columns.get_loc(col)] = True

        # también al revés
        for n in neg_idx:

            nearby_pos = pos_idx[
                (pos_idx > n) &
                (pos_idx - n <= segment_th)
            ]

            if len(nearby_pos) > 0:

                p = nearby_pos[0]

                mask_transient.iloc[n:p+1,
                                    mask_transient.columns.get_loc(col)] = True

    # FINAL MASK

    final_mask = (
        mask_stuck |
        zscore_mask |
        mask_transient
    )

    # apply mask to temperatures
    df_Clean_per[variables] = (
        df_Clean_per[variables]
        .mask(final_mask)
    )

    return df_Clean_per, returns_per_clean

#Zscores Outliers neighborhood Using Zscore Dynamic Jump Lenght

def soil_temp_zscores_neighborhood_outliers(
    df,
    zscr_sd=3,
    th_returns=3,
    sens_stuck=20,
    segment_th=20
):

    variables = df.columns.values

    df_clean = df.copy()

    # RETURNS

    returns, returns_per_clean = conditional_returns(df, th_returns)

    # Z-SCORE GLOBAL (solo referencia para detectar vecindades)

    mean_ret = returns.mean()
    std_ret = returns.std()

    z_temp = (returns - mean_ret) / std_ret

    # outliers por z-score (secundario)
    zscore_mask = z_temp.abs() > zscr_sd*std_ret

    # STUCK SENSOR

    mask_stuck = pd.DataFrame(False, index=returns.index, columns=returns.columns)

    for col in returns.columns:

        diff = returns[col].diff().abs()

        stuck = diff < 1e-6

        groups = (stuck != stuck.shift()).cumsum()

        run_length = stuck.groupby(groups).transform("sum")

        mask_stuck[col] = run_length >= sens_stuck

    # CHANGE POINT + SEGMENT DETECTION (NUEVO CORE)

    mask_transient = pd.DataFrame(False, index=returns.index, columns=returns.columns)

    for col in returns.columns:

        r = returns[col]

        # diferencias (detecta saltos reales)
        diff = r.diff().abs()

        # umbral dinámico robusto
        threshold = np.nanpercentile(diff.dropna(), 99)

        jump = diff > threshold

        # expandir vecindad del salto (captura bloques largos)
        expanded = jump.copy()

        for i in range(1, segment_th + 1):
            expanded |= jump.shift(i, fill_value=False)
            expanded |= jump.shift(-i, fill_value=False)

        # incluir NaNs dentro del bloque (CLAVE para tu caso)
        expanded |= r.isna().rolling(segment_th, min_periods=1).max().astype(bool)

        mask_transient[col] = expanded.fillna(False)

    # FINAL MASK

    final_mask = (
        mask_stuck |
        zscore_mask |
        mask_transient
    )

    df_clean[variables] = df_clean[variables].mask(final_mask)

    return df_clean, returns_per_clean


# Filling Model 5cm Layer
def soil_temp_model_5cm(X_air_temp,X_air_rad,Y_soil_temp,Y_soil_ret,returns=True,model="lassocv",graphs=True,zoom=5,window_zoom=500):
    if returns:
        Y_model=Y_soil_ret
    else:
        Y_model=Y_soil_temp

    data_5_depth=(pd.concat([X_air_temp,X_air_rad,
                         Y_model['soil_temp_deg_C_at_5_cm_depth']],
                        axis=1).dropna()
                        )
    X_clean = data_5_depth[pd.concat([X_air_temp,X_air_rad],
                            axis=1).columns]
    y_clean = data_5_depth[Y_model['soil_temp_deg_C_at_5_cm_depth'].name]

    # split train/test
    X_train, X_test, y_train, y_test = train_test_split(
        X_clean,
        y_clean,
        test_size=0.2,
        random_state=996
    )

    # Ridge Reg
    if model == "ridge":
        model_5cm = make_pipeline(
            StandardScaler(),
            Ridge(alpha=1.0)
        )

        # Fitting
        model_5cm.fit(X_train, y_train)

        #Coef
        summary = pd.DataFrame({
            "coef": model_5cm.named_steps["ridge"].coef_
        }, index=X_train.columns)

        summary


    # Lasso Reg
    if model == "lasso":

        model_5cm = Lasso(alpha=0.01)

        # Fitting
        model_5cm.fit(X_train, y_train)

        #Coef
        coef_lasso = pd.Series(model_5cm.coef_, index=X_train.columns)
        print(coef_lasso.sort_values())


    #Lasso Using CV
    if model == "lassocv":

        model_5cm = make_pipeline(
            StandardScaler(),
            LassoCV(cv=5)
        )

        # Fitting
        model_5cm.fit(X_train, y_train)
        lasso_CV_steps = model_5cm.named_steps["lassocv"]
        print("Lasso CV Best Alpha: ", lasso_CV_steps.alpha_)

        #Coef
        summary = pd.DataFrame({
            "coef": model_5cm.named_steps["lassocv"].coef_
        }, index=X_train.columns)

        summary

    if model=="nn":
        #model
        model_5cm = Sequential()
        model_5cm.add(Dense(64, input_dim=10))
        model_5cm.add(BatchNormalization())
        model_5cm.add(LeakyReLU(alpha=0.1))

        model_5cm.add(Dense(120))
        model_5cm.add(LeakyReLU(alpha=0.1))
        model_5cm.add(Dropout(0.25))

        model_5cm.add(Dense(32))
        model_5cm.add(LeakyReLU(alpha=0.1))
        model_5cm.add(Dropout(0.25))

        model_5cm.add(Dense(16))
        model_5cm.add(BatchNormalization())
        model_5cm.add(LeakyReLU(alpha=0.1))

        model_5cm.add(Dense(1, activation='linear'))
        model_5cm.summary()

        #Fitting
        np.random.seed(996)
        Batch_size = 400
        optimizer = Adam(learning_rate=0.001)

        model_5cm.compile(loss='mean_squared_error', optimizer=optimizer, metrics=["mean_squared_error"])
        early_stop = EarlyStopping(monitor='mean_squared_error', min_delta=0.000001, patience=20, restore_best_weights=True)
        model_5cm.fit(X_train, y_train, epochs=50, batch_size=Batch_size, verbose=1,callbacks=[early_stop]);

        #Testing
        model_5cm.evaluate(X_test, y_test)

    if model!="nn":
        #score
        score = model_5cm.score(X_test, y_test)
        print("R²:", score)

        #RSME
        y_pred = model_5cm.predict(X_test)

        rmse = np.sqrt(
            mean_squared_error(y_test, y_pred)
        )

        print("RMSE:", rmse)

    # Inputting

    # Missign temp at 5 cm depth
    X=(pd.concat([X_air_temp,X_air_rad],
                            axis=1))
    Y=Y_model['soil_temp_deg_C_at_5_cm_depth']

    # filas donde y falta
    pred_mask = Y.isna()

    X_pred = X.loc[pred_mask]

    valid_pred = X_pred.notna().all(axis=1)

    X_pred = X_pred.loc[valid_pred]

    if returns:

       returns_filled = Y.copy()

       if model=="nn":
          returns_filled.loc[X_pred.index] = model_5cm.predict(X_pred).flatten()
       else:
          returns_filled.loc[X_pred.index] = model_5cm.predict(X_pred)

       temp_filled = Y_soil_temp['soil_temp_deg_C_at_5_cm_depth'].copy()

       for i in range(1, len(temp_filled)):

           # si falta temperatura actual
           if pd.isna(temp_filled.iloc[i]):

               prev_temp = temp_filled.iloc[i - 1]
               ret = returns_filled.iloc[i]

               # solo si ambos existen
               if pd.notna(prev_temp) and pd.notna(ret):
                 temp_filled.iloc[i] = prev_temp + ret
    else:
       temp_filled = Y.copy()
       if model=="nn":
          temp_filled.loc[X_pred.index] = model_5cm.predict(X_pred).flatten()
       else:
          temp_filled.loc[X_pred.index] = model_5cm.predict(X_pred)

    if graphs:

    #Filled Temperature
        plt.figure(figsize=(12,4))

        plt.plot(temp_filled)

        plt.xlabel("Time")
        plt.ylabel("Temperature")

        plt.title("Filled Temperature Series")

        plt.show()


    # Zoom in 5 points graph

        # índices donde originalmente había NaN
        temp=Y_soil_temp['soil_temp_deg_C_at_5_cm_depth']
        np.random.seed(996)

        filled_idx = temp[temp.isna()].index

        # escoger hasta 5 puntos rellenados
        #sample_idx = filled_idx[:5]

        # escoger 10 aleatorios
        sample_idx = np.random.choice(filled_idx, size=zoom, replace=False)

        window = window_zoom  # puntos antes y después

        for idx in sample_idx:

            # posición numérica del índice
            pos = temp.index.get_loc(idx)

            start = max(0, pos - window)
            end = min(len(temp), pos + window + 1)

            # ventana local
            temp_window = temp.iloc[start:end]
            filled_window = temp_filled.iloc[start:end]

            plt.figure(figsize=(10,4))

            # serie rellenada
            plt.plot(
                filled_window.index,
                filled_window.values,
                label="Filled Series"
            )

            # serie original
            plt.plot(
                temp_window.index,
                temp_window.values,
                label="Original Series",
                alpha=0.7
            )

            # punto imputado
            plt.scatter(
                idx,
                temp_filled.loc[idx],
                s=80,
                label=f"Imputed = {temp_filled.loc[idx]:.2f}"
            )

            plt.axvline(idx, linestyle="--", alpha=0.5)

            plt.title(f"Imputation around index {idx}")

            plt.xlabel("Time")
            plt.ylabel("Temperature")

            plt.legend()

            plt.show()
    return temp_filled, returns_filled


# Filling Model All Layers
def soil_temp_model(X_air_temp,X_air_rad,Y_soil_temp,Y_soil_ret,
                         Y_soil_temp_fill, Y_soil_return_fill,
                         returns=True,model="lassocv",graphs=True,zoom=5,
                         window_zoom=500,depth=5):

    returns_filled = None

    if returns:
        Y_model=Y_soil_ret
        Y_fill=Y_soil_return_fill
    else:
        Y_model=Y_soil_temp
        Y_fill=Y_soil_temp_fill

    #Select Layer

    if depth==5:
        Depth_idx='soil_temp_deg_C_at_5_cm_depth'
        neurons=10
    elif depth==20:
        Depth_idx='soil_temp_deg_C_at_20_cm_depth'
        neurons=11
    elif depth==50:
        Depth_idx='soil_temp_deg_C_at_50_cm_depth'
        neurons=12
    elif depth==100:
        Depth_idx='soil_temp_deg_C_at_100_cm_depth'
        neurons=13
    else:
        return "Invalid depth: 5, 20, 50 or 100"

    #Layers used

    Depth_vector=['soil_temp_deg_C_at_5_cm_depth',
                  'soil_temp_deg_C_at_20_cm_depth',
                  'soil_temp_deg_C_at_50_cm_depth',
                  'soil_temp_deg_C_at_100_cm_depth']

    selected_cols = Depth_vector[:Depth_vector.index(Depth_idx)]

    #Cleaning

    data_5_depth=(pd.concat([X_air_temp,X_air_rad,Y_model[selected_cols],
                         Y_model[Depth_idx]],
                        axis=1).dropna()
                        )
    X_clean = data_5_depth[pd.concat([X_air_temp,X_air_rad,
                                      Y_model[selected_cols]],
                            axis=1).columns]
    y_clean = data_5_depth[Y_model[Depth_idx].name]

    # split train/test
    #X_train, X_test, y_train, y_test = train_test_split(
    #    X_clean,
    #    y_clean,
    #    test_size=0.2,
    #    random_state=996
    #)

    split_idx = int(len(X_clean) * 0.8)

    X_train = X_clean.iloc[:split_idx]
    X_test  = X_clean.iloc[split_idx:]

    y_train = y_clean.iloc[:split_idx]
    y_test  = y_clean.iloc[split_idx:]

    # Ridge Reg
    if model == "ridge":
        model_5cm = make_pipeline(
            StandardScaler(),
            Ridge(alpha=1.0)
        )

        # Fitting
        model_5cm.fit(X_train, y_train)

        #Coef
        summary = pd.DataFrame({
            "coef": model_5cm.named_steps["ridge"].coef_
        }, index=X_train.columns)

        summary


    # Lasso Reg
    if model == "lasso":

        #model_5cm = Lasso(alpha=0.01)
        model_5cm = make_pipeline(
            StandardScaler(),
            Lasso(alpha=0.01)
        )

        # Fitting
        model_5cm.fit(X_train, y_train)

        #Coef
        coef_lasso = pd.Series(model_5cm.coef_, index=X_train.columns)
        print(coef_lasso.sort_values())


    # Lasso Using Time-Series CV
    if model == "lassocv":

        # ---------------------------------------------------------
        # External CV: evaluates the predictive performance
        # ---------------------------------------------------------
        tscv = TimeSeriesSplit(n_splits=5)

        fold_results = []

        for fold, (train_idx, val_idx) in enumerate(
            tscv.split(X_train), start=1
        ):

            X_fold_train = X_train.iloc[train_idx]
            y_fold_train = y_train.iloc[train_idx]

            X_fold_val = X_train.iloc[val_idx]
            y_fold_val = y_train.iloc[val_idx]

            # Internal CV to select alpha
            inner_tscv = TimeSeriesSplit(n_splits=5)

            fold_model = make_pipeline(
                StandardScaler(),
                LassoCV(cv=inner_tscv)
            )

            # Fit
            fold_model.fit(X_fold_train, y_fold_train)

            # Prediction on unseen validation fold
            y_fold_pred = fold_model.predict(X_fold_val)

            # -----------------------------
            # Regression metrics
            # -----------------------------

            rmse = np.sqrt(
                mean_squared_error(y_fold_val, y_fold_pred)
            )

            mae = mean_absolute_error(
                y_fold_val,
                y_fold_pred
            )

            r2 = r2_score(
                y_fold_val,
                y_fold_pred
            )

            # -----------------------------
            # Directional accuracy
            # -----------------------------

            # Convert predicted values to a Series
            y_fold_pred = pd.Series(
                y_fold_pred,
                index=y_fold_val.index
            )

            # Mask: only actual non-zero returns
            direction_mask = y_fold_val != 0

            # Actual values without zeros
            y_actual_nonzero = y_fold_val[direction_mask]

            # Predicted values corresponding to those same observations
            y_pred_nonzero = y_fold_pred[direction_mask]

            # Number of observations used for directional evaluation
            n_direction = len(y_actual_nonzero)

            # Actual distribution
            actual_positive_pct = np.mean(y_actual_nonzero > 0)
            actual_negative_pct = np.mean(y_actual_nonzero < 0)

            # Predicted distribution for the same observations
            predicted_positive_pct = np.mean(y_pred_nonzero > 0)
            predicted_negative_pct = np.mean(y_pred_nonzero < 0)

            # Directional accuracy
            directional_accuracy = np.mean(
                np.sign(y_actual_nonzero) == np.sign(y_pred_nonzero)
            )


            # -----------------------------
            # Store results
            # -----------------------------

            fold_results.append({
                "Fold": fold,
                "RMSE": rmse,
                "MAE": mae,
                "R2": r2,
                "Directional_Accuracy": directional_accuracy,
                "Predicted_Positive_%": predicted_positive_pct,
                "Predicted_Negative_%": predicted_negative_pct,
                "Actual_Positive_%": actual_positive_pct,
                "Actual_Negative_%": actual_negative_pct,
                "Alpha": fold_model.named_steps["lassocv"].alpha_
            })

        # Convert to DataFrame
        cv_results = pd.DataFrame(fold_results)

        print("\nTime-Series Cross-Validation Results:")
        print(cv_results)

        print("\nAverage CV performance:")

        print(
            "RMSE:",
            cv_results["RMSE"].mean()
        )

        print(
            "MAE:",
            cv_results["MAE"].mean()
        )

        print(
            "R²:",
            cv_results["R2"].mean()
        )

        print(
            "Directional Accuracy:",
            cv_results["Directional_Accuracy"].mean()
        )

        print(
            "Predicted Positive:",
            cv_results["Predicted_Positive_%"].mean()
        )

        print(
            "Predicted Negative:",
            cv_results["Predicted_Negative_%"].mean()
        )

        # ---------------------------------------------------------
        # Final model
        # ---------------------------------------------------------

        final_tscv = TimeSeriesSplit(n_splits=5)

        model_5cm = make_pipeline(
            StandardScaler(),
            LassoCV(cv=final_tscv)
        )

        model_5cm.fit(X_train, y_train)

        lasso_CV_steps = model_5cm.named_steps["lassocv"]

        print(
            "\nFinal Lasso CV Best Alpha:",
            lasso_CV_steps.alpha_
        )

        # Coefficients
        summary = pd.DataFrame({
            "coef": lasso_CV_steps.coef_
        }, index=X_train.columns)


    if model=="nn":
        #model
        model_5cm = Sequential()
        model_5cm.add(Dense(64, input_dim=neurons))
        model_5cm.add(BatchNormalization())
        model_5cm.add(LeakyReLU(alpha=0.1))

        model_5cm.add(Dense(120))
        model_5cm.add(LeakyReLU(alpha=0.1))
        model_5cm.add(Dropout(0.25))

        model_5cm.add(Dense(32))
        model_5cm.add(LeakyReLU(alpha=0.1))
        model_5cm.add(Dropout(0.25))

        model_5cm.add(Dense(16))
        model_5cm.add(BatchNormalization())
        model_5cm.add(LeakyReLU(alpha=0.1))

        model_5cm.add(Dense(1, activation='linear'))
        model_5cm.summary()

        #Fitting
        np.random.seed(996)
        Batch_size = 400
        optimizer = Adam(learning_rate=0.001)

        model_5cm.compile(loss='mean_squared_error', optimizer=optimizer, metrics=["mean_squared_error"])

        #early_stop = EarlyStopping(monitor='mean_squared_error', min_delta=0.000001, patience=20, restore_best_weights=True)
        early_stop = EarlyStopping(
            monitor='val_loss',
            patience=20,
            restore_best_weights=True
        )


        scaler_X = StandardScaler()
        X_train_scaled = scaler_X.fit_transform(X_train)
        X_test_scaled = scaler_X.transform(X_test)

        #model_5cm.fit(X_train, y_train, epochs=50, batch_size=Batch_size, verbose=1,callbacks=[early_stop]);
        model_5cm.fit(
            X_train_scaled,
            y_train,
            validation_split=0.2,
            batch_size=Batch_size,
            verbose=1,
            callbacks=[early_stop]
        )


        #Testing
        model_5cm.evaluate(X_test, y_test)

    if model!="nn":
        #score
        score = model_5cm.score(X_test, y_test)
        print("R²:", score)

        #RSME
        y_pred = model_5cm.predict(X_test)

        rmse = np.sqrt(
            mean_squared_error(y_test, y_pred)
        )

        print("RMSE:", rmse)

        #Final Accuracy

        if returns:

            direction_mask = y_test != 0

            y_test_nonzero = y_test[direction_mask]
            y_pred_nonzero = pd.Series(
                y_pred,
                index=y_test.index
            )[direction_mask]

            test_directional_accuracy = np.mean(
                np.sign(y_test_nonzero) ==
                np.sign(y_pred_nonzero)
            )

            print(
                "Test Directional Accuracy:",
                test_directional_accuracy
            )

    # Inputting

    # Missign temp at Depth cm depth
    X=(pd.concat([X_air_temp,X_air_rad,Y_fill[selected_cols]],
                            axis=1))
    Y=Y_model[Depth_idx]

    # filas donde y falta
    pred_mask = Y.isna()

    X_pred = X.loc[pred_mask]

    valid_pred = X_pred.notna().all(axis=1)

    X_pred = X_pred.loc[valid_pred]

    if returns:

       returns_filled = Y.copy()

       if model=="nn":
          returns_filled.loc[X_pred.index] = model_5cm.predict(X_pred).flatten()
       else:
          returns_filled.loc[X_pred.index] = model_5cm.predict(X_pred)

       temp_filled = Y_soil_temp[Depth_idx].copy()

       for i in range(1, len(temp_filled)):

           # si falta temperatura actual
           if pd.isna(temp_filled.iloc[i]):

               prev_temp = temp_filled.iloc[i - 1]
               ret = returns_filled.iloc[i]

               # solo si ambos existen
               if pd.notna(prev_temp) and pd.notna(ret):
                 temp_filled.iloc[i] = prev_temp + ret
    else:
       temp_filled = Y.copy()
       if model=="nn":
          temp_filled.loc[X_pred.index] = model_5cm.predict(X_pred).flatten()
       else:
          temp_filled.loc[X_pred.index] = model_5cm.predict(X_pred)

    if graphs:

    #Filled Temperature
        plt.figure(figsize=(12,4))

        plt.plot(temp_filled)

        plt.xlabel("Time")
        plt.ylabel("Temperature")

        plt.title("Filled Temperature Series")

        plt.show()


    # Zoom in 5 points graph

        # índices donde originalmente había NaN
        temp=Y_soil_temp[Depth_idx]
        np.random.seed(996)

        filled_idx = temp[temp.isna()].index

        # escoger hasta 5 puntos rellenados
        #sample_idx = filled_idx[:5]

        # escoger 10 aleatorios
        sample_idx = np.random.choice(filled_idx, size=zoom, replace=False)

        window = window_zoom  # puntos antes y después

        for idx in sample_idx:

            # posición numérica del índice
            pos = temp.index.get_loc(idx)

            start = max(0, pos - window)
            end = min(len(temp), pos + window + 1)

            # ventana local
            temp_window = temp.iloc[start:end]
            filled_window = temp_filled.iloc[start:end]

            plt.figure(figsize=(10,4))

            # serie rellenada
            plt.plot(
                filled_window.index,
                filled_window.values,
                label="Filled Series"
            )

            # serie original
            plt.plot(
                temp_window.index,
                temp_window.values,
                label="Original Series",
                alpha=0.7
            )

            # punto imputado
            plt.scatter(
                idx,
                temp_filled.loc[idx],
                s=80,
                label=f"Imputed = {temp_filled.loc[idx]:.2f}"
            )

            plt.axvline(idx, linestyle="--", alpha=0.5)

            plt.title(f"Imputation around index {idx}")

            plt.xlabel("Time")
            plt.ylabel("Temperature")

            plt.legend()

            plt.show()
    return temp_filled, returns_filled, model_5cm


#Time Filing for long term and returns for shorts

def mix_filling(Y_temp_df,temp_df_filled,ret_df_filled,depth=5,gap_th = 10):

    #Select Layer

    if depth==5:
        Depth_idx='soil_temp_deg_C_at_5_cm_depth'
        neurons=10
    elif depth==20:
        Depth_idx='soil_temp_deg_C_at_20_cm_depth'
        neurons=11
    elif depth==50:
        Depth_idx='soil_temp_deg_C_at_50_cm_depth'
        neurons=12
    elif depth==100:
        Depth_idx='soil_temp_deg_C_at_100_cm_depth'
        neurons=13
    else:
        return "Invalid depth: 5, 20, 50 or 100"

    Y = Y_temp_df[Depth_idx]

    #gap detection

    gap_mask = Y.isna()

    groups = (
        gap_mask != gap_mask.shift()
    ).cumsum()

    gap_sizes = (
        gap_mask.groupby(groups)
        .transform("sum")
    )

    #Mask

    short_gap_mask = (
        gap_mask &
        (gap_sizes <= gap_th)
    )

    long_gap_mask = (
        gap_mask &
        (gap_sizes > gap_th)
    )

    #Final Temp

    temp_final = Y.copy()

    #Short Gaps

    temp_final.loc[short_gap_mask] = (
        ret_df_filled.loc[short_gap_mask]

    )

    #Long Gaps

    temp_final.loc[long_gap_mask] = (
        temp_df_filled.loc[long_gap_mask]
    )

    return temp_final



# Moisture Model

def soil_moist_model(X_air_temp,X_air_rad,Y_soil_ret, Y_soil_return_fill,
                         Y_soil_moist, Y_soil_moist_return,
                         Y_soil_moist_fill, Y_soil_moist_return_fill,
                         returns=True,model="lassocv",graphs=True,zoom=5,
                         window_zoom=500,depth=5):

    returns_filled = None

    if returns:
        Y_model=Y_soil_moist_return
        Y_fill=Y_soil_moist_return_fill
    else:
        Y_model=Y_soil_moist
        Y_fill=Y_soil_moist_fill

    #Select Layer

    if depth==5:
        Depth_idx='soil_moisture_percent_at_5_cm_depth'
        neurons=10
    elif depth==20:
        Depth_idx='soil_moisture_percent_at_20_cm_depth'
        neurons=11
    elif depth==50:
        Depth_idx='soil_moisture_percent_at_50_cm_depth'
        neurons=12
    elif depth==100:
        Depth_idx='soil_moisture_percent_at_100_cm_depth'
        neurons=13
    else:
        return "Invalid depth: 5, 20, 50 or 100"

    #Layers used

    Depth_vector=[
        'soil_moisture_percent_at_5_cm_depth',
        'soil_moisture_percent_at_20_cm_depth',
        'soil_moisture_percent_at_50_cm_depth',
        'soil_moisture_percent_at_100_cm_depth'
        ]

    selected_cols = [
        col for col in Depth_vector[:Depth_vector.index(Depth_idx)]
        if col in Y_model.columns and not Y_model[col].isna().all()
    ]



    #idx temp
    if depth==5:
        Depth_idx_temp='soil_temp_deg_C_at_5_cm_depth'
        neurons=10
    elif depth==20:
        Depth_idx_temp='soil_temp_deg_C_at_20_cm_depth'
        neurons=11
    elif depth==50:
        Depth_idx_temp='soil_temp_deg_C_at_50_cm_depth'
        neurons=12
    elif depth==100:
        Depth_idx_temp='soil_temp_deg_C_at_100_cm_depth'
        neurons=13
    else:
        return "Invalid depth: 5, 20, 50 or 100"

    #Layers used

    Depth_vector_temp=['soil_temp_deg_C_at_5_cm_depth',
                  'soil_temp_deg_C_at_20_cm_depth',
                  'soil_temp_deg_C_at_50_cm_depth',
                  'soil_temp_deg_C_at_100_cm_depth']

    selected_cols_temp= Depth_vector_temp[:Depth_vector_temp.index(Depth_idx_temp)+1]

    #Cleaning

    data_5_depth=(pd.concat([X_air_temp,X_air_rad,
                             Y_soil_ret[selected_cols_temp],
                             Y_model[selected_cols],
                             Y_model[Depth_idx]],
                        axis=1).dropna()
                        )
    X_clean = data_5_depth[pd.concat([X_air_temp,X_air_rad,
                                      Y_soil_ret[selected_cols_temp],
                                      Y_model[selected_cols]],
                            axis=1).columns]
    y_clean = data_5_depth[Y_model[Depth_idx].name]

    # split train/test
    #X_train, X_test, y_train, y_test = train_test_split(
    #    X_clean,
    #    y_clean,
    #    test_size=0.2,
    #    random_state=996
    #)

    split_idx = int(len(X_clean) * 0.8)

    X_train = X_clean.iloc[:split_idx]
    X_test  = X_clean.iloc[split_idx:]

    y_train = y_clean.iloc[:split_idx]
    y_test  = y_clean.iloc[split_idx:]

    # Ridge Reg
    if model == "ridge":
        model_5cm = make_pipeline(
            StandardScaler(),
            Ridge(alpha=1.0)
        )

        # Fitting
        model_5cm.fit(X_train, y_train)

        #Coef
        summary = pd.DataFrame(
            {"coef": model_5cm.named_steps["ridge"].coef_},
            index=X_train.columns
        )

        summary


    # Lasso Reg
    if model == "lasso":

        #model_5cm = Lasso(alpha=0.01)
        model_5cm = make_pipeline(
            StandardScaler(),
            Lasso(alpha=0.01)
        )

        # Fitting
        model_5cm.fit(X_train, y_train)

        #Coef
        coef_lasso = pd.Series(model_5cm.coef_, index=X_train.columns)
        print(coef_lasso.sort_values())


    # Lasso Using Time-Series CV
    if model == "lassocv":

        # ---------------------------------------------------------
        # External CV: evaluates the predictive performance
        # ---------------------------------------------------------
        tscv = TimeSeriesSplit(n_splits=5)

        fold_results = []

        for fold, (train_idx, val_idx) in enumerate(
            tscv.split(X_train), start=1
        ):

            X_fold_train = X_train.iloc[train_idx]
            y_fold_train = y_train.iloc[train_idx]

            X_fold_val = X_train.iloc[val_idx]
            y_fold_val = y_train.iloc[val_idx]

            # Internal CV to select alpha
            inner_tscv = TimeSeriesSplit(n_splits=5)

            fold_model = make_pipeline(
                StandardScaler(),
                LassoCV(cv=inner_tscv)
            )

            # Fit
            fold_model.fit(X_fold_train, y_fold_train)

            # Prediction on unseen validation fold
            y_fold_pred = fold_model.predict(X_fold_val)

            # -----------------------------
            # Regression metrics
            # -----------------------------

            rmse = np.sqrt(
                mean_squared_error(y_fold_val, y_fold_pred)
            )

            mae = mean_absolute_error(
                y_fold_val,
                y_fold_pred
            )

            r2 = r2_score(
                y_fold_val,
                y_fold_pred
            )

            # -----------------------------
            # Directional accuracy
            # -----------------------------

            # Convert predicted values to a Series
            y_fold_pred = pd.Series(
                y_fold_pred,
                index=y_fold_val.index
            )

            # Mask: only actual non-zero returns
            direction_mask = y_fold_val != 0

            # Actual values without zeros
            y_actual_nonzero = y_fold_val[direction_mask]

            # Predicted values corresponding to those same observations
            y_pred_nonzero = y_fold_pred[direction_mask]

            # Number of observations used for directional evaluation
            n_direction = len(y_actual_nonzero)

            # Actual distribution
            actual_positive_pct = np.mean(y_actual_nonzero > 0)
            actual_negative_pct = np.mean(y_actual_nonzero < 0)

            # Predicted distribution for the same observations
            predicted_positive_pct = np.mean(y_pred_nonzero > 0)
            predicted_negative_pct = np.mean(y_pred_nonzero < 0)

            # Directional accuracy
            directional_accuracy = np.mean(
                np.sign(y_actual_nonzero) == np.sign(y_pred_nonzero)
            )


            # -----------------------------
            # Store results
            # -----------------------------

            fold_results.append({
                "Fold": fold,
                "RMSE": rmse,
                "MAE": mae,
                "R2": r2,
                "Directional_Accuracy": directional_accuracy,
                "Predicted_Positive_%": predicted_positive_pct,
                "Predicted_Negative_%": predicted_negative_pct,
                "Actual_Positive_%": actual_positive_pct,
                "Actual_Negative_%": actual_negative_pct,
                "Alpha": fold_model.named_steps["lassocv"].alpha_
            })

        # Convert to DataFrame
        cv_results = pd.DataFrame(fold_results)

        print("\nTime-Series Cross-Validation Results:")
        print(cv_results)

        print("\nAverage CV performance:")

        print(
            "RMSE:",
            cv_results["RMSE"].mean()
        )

        print(
            "MAE:",
            cv_results["MAE"].mean()
        )

        print(
            "R²:",
            cv_results["R2"].mean()
        )

        print(
            "Directional Accuracy:",
            cv_results["Directional_Accuracy"].mean()
        )

        print(
            "Predicted Positive:",
            cv_results["Predicted_Positive_%"].mean()
        )

        print(
            "Predicted Negative:",
            cv_results["Predicted_Negative_%"].mean()
        )

        # ---------------------------------------------------------
        # Final model
        # ---------------------------------------------------------

        final_tscv = TimeSeriesSplit(n_splits=5)

        model_5cm = make_pipeline(
            StandardScaler(),
            LassoCV(cv=final_tscv)
        )

        model_5cm.fit(X_train, y_train)

        lasso_CV_steps = model_5cm.named_steps["lassocv"]

        print(
            "\nFinal Lasso CV Best Alpha:",
            lasso_CV_steps.alpha_
        )

        # Coefficients
        summary = pd.DataFrame({
            "coef": lasso_CV_steps.coef_
        }, index=X_train.columns)

    if model=="nn":
        #model
        model_5cm = Sequential()
        model_5cm.add(Dense(64, input_dim=neurons))
        model_5cm.add(BatchNormalization())
        model_5cm.add(LeakyReLU(alpha=0.1))

        model_5cm.add(Dense(120))
        model_5cm.add(LeakyReLU(alpha=0.1))
        model_5cm.add(Dropout(0.25))

        model_5cm.add(Dense(32))
        model_5cm.add(LeakyReLU(alpha=0.1))
        model_5cm.add(Dropout(0.25))

        model_5cm.add(Dense(16))
        model_5cm.add(BatchNormalization())
        model_5cm.add(LeakyReLU(alpha=0.1))

        model_5cm.add(Dense(1, activation='linear'))
        model_5cm.summary()

        #Fitting
        np.random.seed(996)
        Batch_size = 400
        optimizer = Adam(learning_rate=0.001)

        model_5cm.compile(loss='mean_squared_error', optimizer=optimizer, metrics=["mean_squared_error"])

        #early_stop = EarlyStopping(monitor='mean_squared_error', min_delta=0.000001, patience=20, restore_best_weights=True)
        early_stop = EarlyStopping(
            monitor='val_loss',
            patience=20,
            restore_best_weights=True
        )


        scaler_X = StandardScaler()
        X_train_scaled = scaler_X.fit_transform(X_train)
        X_test_scaled = scaler_X.transform(X_test)

        #model_5cm.fit(X_train, y_train, epochs=50, batch_size=Batch_size, verbose=1,callbacks=[early_stop]);
        model_5cm.fit(
            X_train_scaled,
            y_train,
            validation_split=0.2,
            batch_size=Batch_size,
            verbose=1,
            callbacks=[early_stop]
        )


        #Testing
        model_5cm.evaluate(X_test, y_test)

    if model!="nn":
        #score
        score = model_5cm.score(X_test, y_test)
        print("R²:", score)

        #RSME
        y_pred = model_5cm.predict(X_test)

        rmse = np.sqrt(
            mean_squared_error(y_test, y_pred)
        )

        print("RMSE:", rmse)

        #Direction Accuracy Final

        if returns:

            direction_mask = y_test != 0

            y_test_nonzero = y_test[direction_mask]
            y_pred_nonzero = pd.Series(
                y_pred,
                index=y_test.index
            )[direction_mask]

            test_directional_accuracy = np.mean(
                np.sign(y_test_nonzero) ==
                np.sign(y_pred_nonzero)
            )

            print(
                "Test Directional Accuracy:",
                test_directional_accuracy
            )

    # Inputting

    # Missing values at Depth cm depth
    X=(pd.concat([X_air_temp,X_air_rad,
                  Y_soil_return_fill[selected_cols_temp],
                  Y_fill[selected_cols]],
                            axis=1))
    Y=Y_model[Depth_idx]

    # filas donde y falta
    pred_mask = Y.isna()

    X_pred = X.loc[pred_mask]

    valid_pred = X_pred.notna().all(axis=1)

    X_pred = X_pred.loc[valid_pred]

    if returns:

       returns_filled = Y.copy()

       if model=="nn":
          returns_filled.loc[X_pred.index] = model_5cm.predict(X_pred).flatten()
       else:
          returns_filled.loc[X_pred.index] = model_5cm.predict(X_pred)

       moist_filled = Y_soil_moist[Depth_idx].copy()

       for i in range(1, len(moist_filled)):

           # si falta humedad actual
           if pd.isna(moist_filled.iloc[i]):

               prev_moist = moist_filled.iloc[i - 1]
               ret = returns_filled.iloc[i]

               # solo si ambos existen
               if pd.notna(prev_moist) and pd.notna(ret):
                 moist_filled.iloc[i] = prev_moist + ret
    else:
       moist_filled = Y.copy()
       if model=="nn":
          moist_filled.loc[X_pred.index] = model_5cm.predict(X_pred).flatten()
       else:
          moist_filled.loc[X_pred.index] = model_5cm.predict(X_pred)

    if graphs:

    #Filled Moisture
        plt.figure(figsize=(12,4))

        plt.plot(moist_filled)

        plt.xlabel("Time")
        plt.ylabel("Moisture Percentage")

        plt.title("Filled Moisture Series")

        plt.show()


    # Zoom in 5 points graph

        # índices donde originalmente había NaN
        temp=Y_soil_moist[Depth_idx]
        np.random.seed(996)

        filled_idx = temp[temp.isna()].index

        # escoger hasta 5 puntos rellenados
        #sample_idx = filled_idx[:5]

        # escoger 10 aleatorios
        sample_idx = np.random.choice(filled_idx, size=zoom, replace=False)

        window = window_zoom  # puntos antes y después

        for idx in sample_idx:

            # posición numérica del índice
            pos = temp.index.get_loc(idx)

            start = max(0, pos - window)
            end = min(len(temp), pos + window + 1)

            # ventana local
            temp_window = temp.iloc[start:end]
            filled_window = moist_filled.iloc[start:end]

            plt.figure(figsize=(10,4))

            # serie rellenada
            plt.plot(
                filled_window.index,
                filled_window.values,
                label="Filled Series"
            )

            # serie original
            plt.plot(
                temp_window.index,
                temp_window.values,
                label="Original Series",
                alpha=0.7
            )

            # punto imputado
            plt.scatter(
                idx,
                moist_filled.loc[idx],
                s=80,
                label=f"Imputed = {moist_filled.loc[idx]:.2f}"
            )

            plt.axvline(idx, linestyle="--", alpha=0.5)

            plt.title(f"Imputation around index {idx}")

            plt.xlabel("Time")
            plt.ylabel("Moisture Percentage")

            plt.legend()

            plt.show()
    return moist_filled, returns_filled, model_5cm


# Mixed Filling Model Moisture

def mix_filling_moisture(Y_mois_df,mois_df_filled,ret_df_filled,depth=5,gap_th = 10):

    #Select Layer

    if depth==5:
        Depth_idx='soil_moisture_percent_at_5_cm_depth'
        neurons=10
    elif depth==20:
        Depth_idx='soil_moisture_percent_at_20_cm_depth'
        neurons=11
    elif depth==50:
        Depth_idx='soil_moisture_percent_at_50_cm_depth'
        neurons=12
    elif depth==100:
        Depth_idx='soil_moisture_percent_at_100_cm_depth'
        neurons=13
    else:
        return "Invalid depth: 5, 20, 50 or 100"

    Y = Y_mois_df[Depth_idx]

    #gap detection

    gap_mask = Y.isna()

    groups = (
        gap_mask != gap_mask.shift()
    ).cumsum()

    gap_sizes = (
        gap_mask.groupby(groups)
        .transform("sum")
    )

    #Mask

    short_gap_mask = (
        gap_mask &
        (gap_sizes <= gap_th)
    )

    long_gap_mask = (
        gap_mask &
        (gap_sizes > gap_th)
    )

    #Final Temp

    temp_final = Y.copy()

    #Short Gaps

    temp_final.loc[short_gap_mask] = (
        ret_df_filled.loc[short_gap_mask]

    )

    #Long Gaps

    temp_final.loc[long_gap_mask] = (
        mois_df_filled.loc[long_gap_mask]
    )

    return temp_final